name: Update Tools List

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-tools:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch GitHub repos and write to _data/repos.json
        run: |
          # Fetch public repos, select only name, html_url, description, language
          curl -s "https://api.github.com/users/B4l3rI0n/repos?per_page=100" \
            | jq 'map({
                name: .name,
                html_url: .html_url,
                description: (.description // ""),
                language: (.language // "")
              })' \
            > _data/repos.json

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/repos.json
          git diff --quiet && echo "No changes to repos.json" || (
            git commit -m "ci: update repos.json"
            git push
          )
          